apiVersion: v1
kind: Service
metadata:
  labels:
    app: oes
    component: auditclient-v311
  name: oes-audit-client-v311
spec:
  ports:
    - name: auditclient
      port: 8098
      protocol: TCP
      targetPort: 8098
  selector:
    app: oes
    component: auditclient-v311
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oes
    component: auditservice-v311
  name: oes-audit-service-v311
spec:
  ports:
    - name: auditservice
      port: 8097
      protocol: TCP
      targetPort: 8097
  selector:
    app: oes
    component: auditservice-v311
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
data:
  audit-local.yml: >-
    ICAgIHNwcmluZzoKICAgICAgZGF0YXNvdXJjZToKICAgICAgICB1cmw6IGpkYmM6cG9zdGdyZXNxbDovL29lcy1kYjo1NDMyL2F1ZGl0ZGIKICAgICAgICB1c2VybmFtZTogcG9zdGdyZXMKICAgICAgICBwYXNzd29yZDogbmV0d29ya3MxMjMKICAgIGxvZ2dpbmc6CiAgICAgIGxldmVsOgogICAgICAgIGNvbS5vcHNteC5hdWRpdGNsaWVudHNlcnZpY2U6IElORk8KICAgIG9lczoKICAgICAgYWRtaW46CiAgICAgICAgdXNlcjogYWRtaW4KICAgIGZlaWduOgogICAgICBjbGllbnQ6CiAgICAgICAgY29uZmlnOgogICAgICAgICAgZGVmYXVsdDoKICAgICAgICAgICAgY29ubmVjdFRpbWVvdXQ6IDUwMDAKICAgICAgICAgICAgcmVhZFRpbWVvdXQ6IDUwMDAKICAgICAgICAgICAgbG9nZ2VyTGV2ZWw6IGJhc2ljCiAgICAgICAgcGxhdGZvcm1zZXJ2aWNlOgogICAgICAgICAgbmFtZTogcGxhdGZvcm1zZXJ2aWNlCiAgICAgICAgICB1cmw6IGh0dHA6Ly9vZXMtcGxhdGZvcm06ODA5NQogICAgICAgIHZpc2liaWxpdHlzZXJ2aWNlOgogICAgICAgICAgbmFtZTogdmlzaWJpbGl0eXNlcnZpY2UKICAgICAgICAgIHVybDogaHR0cDovL29lcy12aXNpYmlsaXR5OjgwOTY=
kind: Secret
metadata:
  labels:
    app: oes
    component: auditclient-v311
  name: oes-audit-client-config-v311
type: Opaque
---
apiVersion: v1
data:
  audit-local.yml: >-
    ICAgIHNwcmluZzoKICAgICAgZGF0YXNvdXJjZToKICAgICAgICB1cmw6IGpkYmM6cG9zdGdyZXNxbDovL29lcy1kYjo1NDMyL2F1ZGl0ZGIKICAgICAgICB1c2VybmFtZTogcG9zdGdyZXMKICAgICAgICBwYXNzd29yZDogbmV0d29ya3MxMjMKICAgIGxvZ2dpbmc6CiAgICAgIGxldmVsOgogICAgICAgIGNvbS5vcHNteC5hdWRpdHNlcnZpY2U6IElORk8KICAgIGZlaWduOgogICAgICBjbGllbnQ6CiAgICAgICAgY29uZmlnOgogICAgICAgICAgZGVmYXVsdDoKICAgICAgICAgICAgY29ubmVjdFRpbWVvdXQ6IDEwMDAwMAogICAgICAgICAgICByZWFkVGltZW91dDogMTAwMDAwCiAgICAgICAgICAgIGxvZ2dlckxldmVsOiBiYXNpYwogICAgICAgIHBsYXRmb3Jtc2VydmljZToKICAgICAgICAgIG5hbWU6IHBsYXRmb3Jtc2VydmljZQogICAgICAgICAgdXJsOiBodHRwOi8vb2VzLXBsYXRmb3JtOjgwOTUKICAgICAgICBhdWRpdGNsaWVudHNlcnZpY2U6CiAgICAgICAgICBuYW1lOiBhdWRpdGNsaWVudHNlcnZpY2UKICAgICAgICAgIHVybDogaHR0cDovL29lcy1hdWRpdC1jbGllbnQtdjMxMTo4MDk4CiAgICAgICAgb2VzOgogICAgICAgICAgdXJsOiBodHRwOi8vb2VzLXNhcG9yOjgwODUKICAgICAgICBhdXRvcGlsb3Q6CiAgICAgICAgICB1cmw6IGh0dHA6Ly9vZXMtYXV0b3BpbG90OjgwOTAKICAgICAgICB2aXNpYmlsaXR5c2VydmljZToKICAgICAgICAgIHVybDogaHR0cDovL29lcy12aXNpYmlsaXR5OjgwOTYKICAgICAgICBkYXNoYm9hcmQ6CiAgICAgICAgICB1cmw6IGh0dHA6Ly9vZXMtZGFzaGJvYXJkOjgwOTQ=
kind: Secret
metadata:
  labels:
    app: oes
    component: auditservice-v311
  name: oes-audit-service-config-v311
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oes
    component: auditservice-v311
  name: oes-audit-service-v311
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oes
      component: auditservice-v311
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: oes
        component: auditservice-v311
    spec:
      containers:
        - image: 'quay.io/opsmxpublic/ubi8-oes-audit-service:v3.11.1'
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /mgmt/health
              port: 8097
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 1
          name: oes-audit-service-v311
          ports:
            - containerPort: 8097
              name: backend
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8097
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 1000m
              memory: 1000Mi
            requests:
              cpu: 500m
              memory: 500Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /opsmx/conf/audit-service-local.yml
              name: audit-config-volume
              subPath: audit-local.yml
            - mountPath: /opsmx/conf/bootstrap.yml
              name: bootstrap-config-volume
              subPath: bootstrap.yml
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: opsmxdev-secret
        - name: opsmx11-secret
      initContainers:
        - command:
            - /bin/bash
            - '-c'
            - >-
              sleep 30;echo Waiting for oes-db to be up and running; pg_isready
              -h oes-db -p 5432 && echo PostgreSQL DB is ready to receive
              connections
          image: 'postgres:9.6.5'
          imagePullPolicy: IfNotPresent
          name: db-check
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: audit-config-volume
          secret:
            defaultMode: 420
            items:
              - key: audit-local.yml
                path: audit-local.yml
            secretName: oes-audit-service-config-v311
        - name: bootstrap-config-volume
          secret:
            defaultMode: 420
            items:
              - key: bootstrap.yml
                path: bootstrap.yml
            secretName: bootstrap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oes
    component: auditclient-v311
  name: oes-audit-client-v311
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oes
      component: auditclient-v311
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: oes
        component: auditclient-v311
    spec:
      containers:
        - image: 'quay.io/opsmxpublic/ubi8-oes-audit-client:v3.11.1'
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /mgmt/health
              port: 8098
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 1
          name: oes-audit-client-v311
          ports:
            - containerPort: 8098
              name: backend
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8098
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 1000m
              memory: 1000Mi
            requests:
              cpu: 500m
              memory: 500Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /opsmx/conf/audit-client-local.yml
              name: audit-config-volume
              subPath: audit-local.yml
            - mountPath: /opsmx/conf/bootstrap.yml
              name: bootstrap-config-volume
              subPath: bootstrap.yml
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: opsmxdev-secret
        - name: opsmx11-secret
      initContainers:
        - command:
            - /bin/bash
            - '-c'
            - >-
              sleep 30;echo Waiting for oes-db to be up and running; pg_isready
              -h oes-db -p 5432 && echo PostgreSQL DB is ready to receive
              connections
          image: 'postgres:9.6.5'
          imagePullPolicy: IfNotPresent
          name: db-check
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: audit-config-volume
          secret:
            defaultMode: 420
            items:
              - key: audit-local.yml
                path: audit-local.yml
            secretName: oes-audit-client-config-v311
        - name: bootstrap-config-volume
          secret:
            defaultMode: 420
            items:
              - key: bootstrap.yml
                path: bootstrap.yml
            secretName: bootstrap

