apiVersion: batch/v1
kind: Job
metadata:
  generateName: isd-db-migrate
  labels:
    app: isd-install
spec:
  backoffLimit: 2
  template:
    spec:
      containers:
        - args:
            - |-
              set +x
              source /repo/environment
              export source=3.10
              cd /repo/oes-data-migration-scripts/
              ls -ltra

              echo "upgrading  v3.10 to v3.11"

              python3 migration_v3.10.x_to_v3.11.py auditdb $host opsmx $host http://oes-audit-service-v311:8097 $port $pguser $pgpassword

          command:
            - /bin/bash
            - +x
            - '-c'
          envFrom:
            - configMapRef:
                name: upgrade-inputcm
          image: 'quay.io/opsmxpublic/ubi8-oes-platform:v3.12.5'
          name: exec-db-upgrade
          volumeMounts:
            - mountPath: /repo
              name: repo-volume
      initContainers:
        - args:
            - |-

              export ns="$namespace"

              source /home/opsmx/scripts/db_migration_script.sh

              ls -ltra  /repo/
          command:
            - /bin/bash
            - +x
            - '-c'
          envFrom:
            - configMapRef:
                name: upgrade-inputcm
          image: 'quay.io/opsmxpublic/opsmx-custom-binaries:opsmx-isd-scripts'
          name: get-script
          volumeMounts:
            - mountPath: /repo
              name: repo-volume
      restartPolicy: Never
      serviceAccountName: isd-install
      volumes:
        - emptyDir: {}
          name: repo-volume

