apiVersion: batch/v1
kind: Job
metadata:
  generateName: delete-services
  labels:
    app: isd-install
spec:
  backoffLimit: 2
  template:
    spec:
      containers:
        - args:
            - |-
              set +x
              source /repo/environment

              export ns="$namespace"

              kubectl delete svc,cm,secrets,deploy --all -l component=auditclient-v311 -n $ns

              kubectl delete svc,cm,secrets,deploy --all -l component=auditservice-v311 -n $ns

          command:
            - /bin/bash
            - +x
            - '-c'
          envFrom:
            - configMapRef:
                name: upgrade-inputcm
          image: 'quay.io/opsmxpublic/ubi8-oes-platform:v3.12.5'
          name: delete-svc-audit
          volumeMounts:
            - mountPath: /repo
              name: repo-volume
      restartPolicy: Never
      serviceAccountName: isd-install
      volumes:
        - emptyDir: {}
          name: repo-volume

