apiVersion: v1
kind: ServiceAccount
metadata:
  name: byos
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: byos
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: byos
    namespace: opsmx-isd #Please update the namespace
