apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 'pvc-isd311-minio'
  namespace: opsmx-isd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
